### ISSUE TITLE
Not all phantomJS browsers in the pool closing reliably

### ISSUE THREAD

**Issue by janexner** [janexner/analytics-tests-test#1]
Often, after a test run, there will be one or more phantomJS instances still alive in the system.

**Comment by janexner** [comment]
Fixed on 160530.

driver.quit() works so much better than driver.close()...

**Comment by kkashyap1707** [comment]
Please have a look into the below-mentioned error and Provide the solution for it.

**Steps Performed:-:** 
Download the project
Go to project directory
run the project using: mvn test



After Running test I got below error :-: 

 **T E S T S
-------------------------------------------------------
Running com.exner.tools.analyticstdd.SiteInfrastructureTests.AllTests
Mar 05, 2017 8:40:34 PM com.exner.tools.analyticstdd.SiteInfrastructureTests.AllTests$1 setUp
INFO: Setting up web driver pool
Mar 05, 2017 8:40:34 PM com.exner.tools.analyticstdd.SiteInfrastructureTests.BasePooledWebDriverFactory create
INFO: Creating WebDriver
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.095 sec <<< FAILURE! - in com.exner.tools.analyticstdd.SiteInfrastructureTests.AllTests
jQuery loaded - http://www.jan-exner.de/(com.exner.tools.analyticstdd.SiteInfrastructureTests.tests.JQueryLoadedTestCase)  Time elapsed: 0.046 sec  <<< ERROR!
java.lang.IllegalStateException: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html


Results :

Tests in error: 
  JQueryLoadedTestCase>WebDriverBasedTestCase.setUp:31 » IllegalState The path t...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0**

**Comment by janexner** [comment]
Hmm... is phanomtJS actually in your system path? In other words: when you're on a command line and just type phantomjs --version, what happens?

**Comment by kkashyap1707** [comment]
@janexner In my system phantomJS is not installed that's why issue occurred. Thanks for your quick response.
